### ISSUE TITLE
introduce capability to pass parameters into nodejs runtime

### ISSUE THREAD

**Issue by OscarScholten** [forcedotcom/sfdx-core#110]
Hi,

I am using a 3rd party SFDX plugin that uses a lot of memory; it often fails with the following generic NodeJS out-of-memory error message:

> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

As a solution, I've done a bit of hacking and changed

`"%~dp0node.exe" "%~dp0%BIN_NAME%.js" %*`

into

`"%~dp0node.exe" --max-old-space-size=8192 "%~dp0%BIN_NAME%.js" %*`

In my C:\Users\Oscar\AppData\Local\sfdx\client\bin\sfdx.cmd

This works for now, the plugin allocates up to 2.5GB and is happy.

However, I'm not sure this little hack will survive the next update of the CLI tooling, and I'd rather not have to ask all my 20 team members that also need to run this plugin to make these changes, so I'd prefer to make a pull request to one of the SFDX or oclif repos and make it more generically available. I was thinking of using an environment variable for these kind of settings.

Could you give me some pointers "where" to contribute this? I browsed this repository and some others but could not find any references to sfdx.cmd. I'm not very familiar with oclif, I can imagine those files are actually generated by that framework somehow.

Cheers, Oscar

**Comment by rbergman** [comment]
You can set the `NODE_OPTIONS=--max-old-space-size=8192` environment variable to pass this through the CLI to the node exe without hacking the CLI launch script.

**Comment by rbergman** [comment]
Also, the CLI base repository containing the launch scripts like `sfdx.cmd` is not yet open source, though it's something we'd like to eventually do.

**Comment by OscarScholten** [comment]
Excellent! I was hoping NodeJS would provide something like that out-of-the-box but I must have been searching using the wrong keywords. Thanks for pointing me in the right direction, closing the issue.
