### ISSUE TITLE
The generated README.md for an SFDX CLI plugin is broken

### ISSUE THREAD

**Issue by OscarScholten** [forcedotcom/sfdx-core#119]
Hi,

I'm doing some work on an existing SFDX CLI plugin and I noticed a problem when the README.md file is generated. As part of the `prepare` script, the file `oclif.manifest.json` is regenerated and the change I noticed between an old build and a new build is that the new build now includes `usage` properties.

For some reason, those usage properties make the generated README look broken. I've created a fresh plugin and posted it here (Yeoman says it used version 1.0.1, I've used defaults for all questions):

https://github.com/OscarScholten/sfdx-broken-readme

As you can see, the list of commands looks wrong:

> sfdx-broken-readme <%= command.id %> [-n <string>] [-f] [-v <string>] [-u <string>] [--apiversion <string>] [--json] [--loglevel trace|debug|info|warn|error|fatal]

Should be:

> sfdx-broken-readme hello:org [FILE]

I've also posted a small workaround that shows that when you post-process `oclif.manifest.json` and remove all usage properties, the readme does render correctly. See the command `fixreadme` in `package.json`.

I've had a quick peek, the usage property seems to be introduced by SFDX; when I generate a vanilla oclif plugin using:

> npx oclif plugin mynewplugin

The problem does not occur.

Any clue what might be going wrong here?

Cheers, Oscar

**Comment by amtrack** [comment]
related issue: https://github.com/forcedotcom/sfdx-plugin-generate/issues/55

**Comment by amphro** [comment]
Ya, that is the right issue on the right repo, and it should be fixed with the latest version. Closing.
