### ISSUE TITLE
Access token returned from Connection is "stale"

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/sfdx-core#132]
**Is your feature request related to a problem? Please describe.**

I'm running the following code to try and get the access token from a sfdx user

```typescript
            const connection: Connection = await Connection.create({
                authInfo: await AuthInfo.create({ username: config.auth.username })
            });
            let token  = connection.accessToken;
```

However, when I attempt to use the token to hit the API, it appears that the token has expired.  However, if I first run `sfdx force:org:open` with the same user, then the returned token seems to work.

**Describe the solution you'd like**
I'd expect `Connection.create` would go ahead and refresh the token if needed

**Describe alternatives you've considered**
I'm fine with having to manually refresh the token,  However, I've yet to figure out a way to do so from `@salesforce/core`.  I assume it's possible?  Could someone provide an example?

**Comment by ChuckJonas** [comment]
oddly enough, if I use the connection prior to trying to leverage the token elsewhere, it seems to then work...

```typescript
const connection: Connection = await Connection.create({
         authInfo: await AuthInfo.create({ username: config.auth.username })
});
let token  = connection.accessToken;
await connection.query('SELECT Id FROM Account LIMIT 1')
```

**Comment by shetzel** [comment]
There is this: https://forcedotcom.github.io/sfdx-core/classes/org.html#refreshauth

The assumption is that most of the time you're working with the Connection on the Org.  Depending on how you use the connection, it should refresh the token for you (as you just noted).

**Comment by ChuckJonas** [comment]
@shetzel thanks, for the quick response. This is exactly what I needed!   I'm currently just using the `core` library to allow the user to specific `sfdx` as an auth option (however, I do hope to refactor to use it as the client in the future). 

I've run out of stale orgs to test with at the moment, but seems like this should work.  One question related to `refreshAuth()`.  Does it mutate the connection that was passed in (updating the access token)? 

Or do I need to call `org.getConnection()` after refreshing?

Example: 

```typescript
let connection: Connection = await Connection.create({
    authInfo: await AuthInfo.create({ username: config.auth.username }
    )
});
let org = await Org.create({connection});
await org.refreshAuth();
connection = org.getConnection(); //I'm guessing this isn't needed, but just to be safe?
```

**Comment by shetzel** [comment]
You should not need to call `org.getConnection()` after refreshing.  It saves the updated AuthInfo data.

If you're testing it out, you can use the session management in the org to invalidate your sessions.

**Comment by ChuckJonas** [comment]
@shetzel 🙇
