### ISSUE TITLE
Add user who created a sandbox to the auth file for sandbox delete operation.

### ISSUE THREAD

**Issue by khogan18** [forcedotcom/sfdx-core#137]
**Is your feature request related to a problem? Please describe.**
The API command to delete a sandbox org needs to be made against the owning production org.  I need a way to authenticate into the prod org for a given sandbox.

**Describe the solution you'd like**
Add a 'prodOrgUsername' field to AuthInfoFields.  This field would only be used for sandboxes and would contain the user who created the sandbox (prod user).  This field would give me a link to the auth file needed when issuing the command to delete a sandbox.

**Describe alternatives you've considered**
I would have to make an API call to get the prod org associated with the sandbox, then scan all of the auth files to find ones associated with the prod org, then try those files until one worked.

**Additional context**

**Comment by amphro** [comment]
@khogan18 does 147 implement this?

**Comment by khogan18** [comment]
Yes,  147 solves this problem.
