### ISSUE TITLE
Enable "Clear Problems"

### ISSUE THREAD

**Issue by jon-freed** [forcedotcom/sfdx-core#139]
_Submitting this issue here as per @gjsjohnmurray 's suggestion.  From microsoft/vscode/issues/66982

jon-freed [commented](https://github.com/microsoft/vscode/issues/66982#issuecomment-501336687)
> Current workaround: command "Developer: Reload Window"
>
>Another use case for such a "Clear problem(s)" button or command is this:
>
>The extension "salesforce.salesforcedx-vscode" enables a command and a context-menu command "SFDX: Deploy This Source to Org". You can use the command from the Explorer window/pane without even having a file open. If the deployment fails, a "Problem" line will be created. It will go away if you can successfully use that command to deploy that same file, but that isn't always desirable. The current work-around is to do the "Developer: Reload Window" command. But that's quite drastic.
>
>Count me among the people who think a user should be able to clear the "Problems" view/pane like the Output, Debug Console, and Terminal views/panes can be cleared/killed. I did read sandy081 / dbaeumer 's comment(s) why "Clearing problems is not as straight forward", and I still feel (subjectively and perhaps naively) that ultimately, a consistent experience across the views/panes is better. If the problems did not go away upon the "Developer: Reload Window" command, then I might feel differently. But they do.

@gjsjohnmurray [commented](https://github.com/microsoft/vscode/issues/66982#issuecomment-501343354):
>jon-freed [...] I suggest you lobby the developers of "salesforce.salesforcedx-vscode" extension to get them to add an extra command "SFDX: Clear Problems". It's their extension that owns the Problem entries you want rid of.

**Comment by allisonletts** [comment]
I just ran into the same issue. As more people move towards adoption of VSCode for SFDX, the extension pack is likely to encounter some issues. Since VSCode really doesn't want to let you clear the problems on their side, I'd love SFDX to implement some way of basically saying "recheck for these problems" and/or "clear the problem cache."

**Comment by amphro** [comment]
This is not a sfdx-core library feature. I think you meant this repo here: https://github.com/forcedotcom/salesforcedx-vscode I can't transfer the issue so you'll need to recreate the issue there.
