### ISSUE TITLE
Move jsforce dependency to 1.9

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/sfdx-core#141]
So far, sfdx core is using jsforce 1.8.5.
Starting 1.9, jsforce is using sobjects collections for CRUD operations, as explained [here](https://jsforce.github.io/blog/posts/20180726-jsforce19-features.html).

This would save some API calls, as updating 200 records would only use 1 API call instead of 200 today.

**Comment by Jamesdinnes** [comment]
#161 

Created the PR for this, just waiting for sf.

**Comment by adrianlukaszek1992** [comment]
Jamesdinnes did you try to add any  reviewer with write access to your PR, so it can be finally merged?

**Comment by amphro** [comment]
We are trying to fix a security vulnerability in jsforce. Once that is released, we will update and publish a new version. See https://github.com/jsforce/jsforce/pull/930

**Comment by amphro** [comment]
This was merged here https://github.com/forcedotcom/sfdx-core/pull/190/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R48 and released in `2.1.4`
