### ISSUE TITLE
SFDX not pushing all data. No longer pushing permissions sets and many other objects

### ISSUE THREAD

**Issue by jeremiahsherrill** [forcedotcom/sfdx-core#154]
### Summary

When pushing data using the following command
sfdx force:source:push --targetusername <useremail> -f --dev-debug

It pushes most of the data, everything seems successful, but a lot of the information in the generated mdapipkg folder are not getting pushed.  Including certain objects and permission sets.  It doesn't error out and the debug log does not show any problems.   

### Expected result

I am expecting all data within the mdapi package to be pushed to the sandbox, not just partial information. 

### Additional information

@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 46.4.0 (core)
├─ force-language-services 46.9.0 (core)
└─ salesforce-alm 46.8.0 (core)

sfdx-cli 7.14.0 (core)

Windows 10 Professional

**Comment by clairebianchi** [comment]
@jeremiahsherrill source:push does not work with Sandboxes, its a scratch org command
