### ISSUE TITLE
Can no longer authenticate with any org

### ISSUE THREAD

**Issue by jeromegv** [forcedotcom/sfdx-core#163]
### Summary
I can no longer authenticate with any org

When I run sfdx force:auth:web:login
This open my authentication in a new window. I can login into my salesforce instance but after, this sends me to this URL
http://localhost:1717/OauthRedirect?code=aPrxtI4fE7jL0iTE..AhPcArcvFq87gsyewmXz_c9U7.YsMKBYhJwZzYB6IrIj89fzSxT4S7lg%3D%3D&state=fc994e2a3724

And then Firefox is telling me that this server is not found.

sfdx force:auth:web:login
ERROR running force:auth:web:login:  retry your request 

I've tried to switch my browser, I get the same result in Safari.
I have no proxy or any weird configuration, I connect to the internet directly at my home.

The weirdest thing is that this used to work and then today in the middle of the day this just stopped working. I've rebooted my Mac a few times, no difference.

Any idea?
**SFDX CLI Version**
sfdx-cli/7.19.0-c5be43915c darwin-x64 node-v10.15.3
**SFDX plugin Version**:
sfdx-cli 7.19.0 (core)
**OS and version**:
MacOS Mojava 10.14.6

**Comment by tnoonan-salesforce** [comment]
I just tried authenticating and it worked.

Can you run this: `DEBUG=*  sfdx force:auth:web:login`

**Comment by jeromegv** [comment]
This works now, this might have been the issue
 https://status.salesforce.com/generalmessages/239
