### ISSUE TITLE
Auth code exchange fails due to codeVerifier

### ISSUE THREAD

**Issue by khogan18** [forcedotcom/sfdx-core#166]
### Summary

Trying to do an auth code exchange (for web auth) using AuthInfo.save() fails with 'unexpected code verifier'.  

AuthInfo. buildWebAuthConfig() is supposed to do the auth code exchange.  The first thing it does is create a AuthCodeOAuth2 object, which creates a codeVerifier.  When the url is constructed for doing the auth code exchange the code verifier is included as a param (see authInfo._postParams() ).  When the request is received by salesforce core it is rejected because the exchange request contains a code verifier but there is no code challenge.

The user experience is to create a sandbox, and at the end the user is authorized into the sandbox.  No browser is involved.  After the sandbox is created we authenticate into the sandbox and that returns the authcode.  We then want to turn around and exchange the authcode for the tokens.  This is the same user experience as creating a scratch org.  The only difference is the scratch org uses the old style method of calling authorize().  This path does not have the code verifier/challenge change.

### Steps To Reproduce

1.  Create an object with the necessary oauth2Options options (clientId, authcode, instanceUrl, and loginUrl).
1.  Call AAuthInfo.create({<username> , oauth2Options});

### Expected result

The user is authorized and the call returns access and refresh tokens.

### Actual result

The request is denied with 'unexpected code verifier'.  

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.12.3-bfc421fa08 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
salesforce-alm 46.6.1-2 (link) 

**OS and version**:

mac 10.13.6

**Comment by clairebianchi** [comment]
This has been fixed :)
