### ISSUE TITLE
SFDX deploys whole object instead of specified sub type (Weblink)

### ISSUE THREAD

**Issue by eric-bw** [forcedotcom/sfdx-core#172]
### Summary

When I try to deploy a single component related to a custom object, the system ends up deploying all the metadata associated to the object. 

### Steps To Reproduce:

1. generate deploy.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- generated for env debbie.oliver@nbcuni.com.tvba.uat@2019-09-23 11:17:48.454894-->
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
  <types>
    <members>Object__c.VIEW_LINK</members>
    <name>WebLink</name>
  </types>
</Package>
```

2. deploy using the following mechanism: 
`sfdx force:source:deploy -u <env> -x manifest/deploy.xml`

### Expected result

```
FULL NAME                                            TYPE            PROJECT PATH
───────────────────────────────────────────────────  ──────────────  ────────────────────────────────────────────────────────────────────────────────────────────────────────'
Object.View_Link                                   WebLink         force-app/main/default/objects/Deal__c/webLinks/View_Link.webLink-meta.xml
```

### Actual result

```
FULL NAME                                            TYPE            PROJECT PATH
───────────────────────────────────────────────────  ──────────────  ────────────────────────────────────────────────────────────────────────────────────────────────────────'
Object.View_Link                                   WebLink         force-app/main/default/objects/Deal__c/webLinks/View_Link.webLink-meta.xml
+ 50 other sub-objects
```

### Additional information

sfdx-cli/7.19.0 darwin-x64 node-v11.10.0

sfdx plugins --core
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.9.0 (core)
├─ force-language-services 46.13.0 (core)
└─ salesforce-alm 46.12.0 (core)
sfdx-cli 7.19.0 (core)

**OS and version**:
osx 10.14.6

**Comment by eric-bw** [comment]
duplicates https://github.com/forcedotcom/cli/issues/156

**Comment by clairebianchi** [comment]
Closing as the conversation is happening in 156
