### ISSUE TITLE
ERROR running force:source:deploy:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by scolladon** [forcedotcom/sfdx-core#178]
### Summary

when executing sfdx force:source:deploy -x package.xml I have this error systematically :
ERROR running force:source:deploy:  Maximum call stack size exceeded

since friday 4 october 2019

### Steps To Reproduce:

`
sfdx force:source:deploy -x package.xml
`

### Expected result

Deployment running

### Actual result

ERROR running force:source:deploy:  Maximum call stack size exceeded

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.27.0 darwin-x64 node-v10.16.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
etcopydata 0.4.4
generator 1.1.1 (core)
salesforcedx 46.17.0 (core)
├─ force-language-services 46.24.0 (core)
└─ salesforce-alm 46.22.0 (core)

sfdx-cli 7.27.0 (core)

**OS and version**:
Mac OS 10.14.6 (18G103)

**Comment by jamescary** [comment]
@dakotalim54 @scolladon, are you using CustomLabels? One of our project teams were experiencing this issue and after applying the workaround in the Issue linked below, the error has been resolved.

https://github.com/forcedotcom/cli/issues/41#issuecomment-529579809

**Comment by scolladon** [comment]
For me too...
Is there a fix planned ?

**Comment by Meryam4Karazi** [comment]
i get the same problem each time i want to deploy things including CustomLabel,
So a workaround was to deploy the custom labels first, then deploy the rest (exclude custom labels)

**Comment by clairebianchi** [comment]
We are currently working on a fix for this. please follow the other issue https://github.com/forcedotcom/cli/issues/41
I am closing this one as a duplicate
