### ISSUE TITLE
Another Bug: LWCs created by sfdx cannot be deployed if name entered starts with upperCase

### ISSUE THREAD

**Issue by NuAgeDan** [forcedotcom/sfdx-core#184]
### Summary

See title. Error is: No base file for markup://c:LoginProcessCreation. The issue seems to be that the file is created with a lowercase letter, which is good, but is looking for an uppercase letter.

### Steps To Reproduce:

Create an LWC via the VS Code command with the first letter uppercase. Changing the fqn does not fix this problem. 

### Expected result

Force everything you rely on into camelCase rather than just file and folder names. 

### Actual result

See above.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):

**OS and version**: Latest version of Win 10.   47.2 on plugins. Latest (7.28....) on sfdx

**Comment by clairebianchi** [comment]
@NuAgeDan We have a fix for this going out in this Thursday's release. Please update your CLI after Thursday and let me know if you are still experiencing the issue.

**Comment by NuAgeDan** [comment]
Thanks @clairebianchi! Will do
