### ISSUE TITLE
Provide mechanism for using the clientSecret unencrypted

### ISSUE THREAD

**Issue by khogan18** [forcedotcom/sfdx-core#202]
This repository only supports the Salesforce CLI Core libraries if you have a feature request that is not related to the Core Libraries but instead to the Salesforce CLI or the force commands please submit your issue to the forcedotcome/cli repo not this one. 

**Is your feature request related to a problem? Please describe.**
I'm adding functionality to authorize/authenticate into a newly created sandbox.  The user will be automatically logged into the sandbox using the same mechanism used to log into the production org.  This is already supported for JWT and I'm extending the functionality to support web auth.  Unfortunately the clientSecret cannot be reused for the sandbox as the secret is encrypted in AuthFields.  

**Describe the solution you'd like**
I would like a mechanism to reuse a user's credentials to log into a different org.  I need to either get the clientSecret unencrypted or a mechanism to log into an org using the user's existing credentials.

**Describe alternatives you've considered**
I have not found a way to access a user's decrypted clientSecret from the toolbelt.

**Additional context**

**Comment by amphro** [comment]
The PR fixes this by allowing you to specify a parent authinfo to get the connection details, rather than accessing the clientSecret directly. 

We can reopen if there is an issue with the PR or the solution.
