### ISSUE TITLE
Security Issue with mkdirp 0.5.1

### ISSUE THREAD

**Issue by JosephAllen** [forcedotcom/sfdx-core#221]
https://github.com/forcedotcom/sfdx-core/blob/0b1098b436d755afc82142de19b0fdb29a4f400f/package.json#L50

mkdirp 0.5.1 has known security issues which is causing compile issues for dependency applications and salesforce extensions.

Can someone update the 'dependencies' section of the package.json to: `"mkdirp": "^1.0.4"`

**Comment by amphro** [comment]
https://github.com/forcedotcom/sfdx-core/pull/228
