### ISSUE TITLE
sfdx plugins:install not working with Private NPM Registry

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/sfdx-core#233]
When running sfdx plugins:install hpe-sfdx-plugins, I receive the following message

![image](https://user-images.githubusercontent.com/55927613/82245811-8ca58780-993b-11ea-94c8-f06289314fe7.png)

If I use the public NPM registry everything works fine. Due to compliance issues I had to migrate my package to a private registry and now I can't install the plugin.
The only thing I changed in the Plugin's package.json was this

![image](https://user-images.githubusercontent.com/55927613/82245946-c4acca80-993b-11ea-9432-be1eb26b3538.png)

Im also able to install the package using ````npm install hpe-sfdx-plugins```` without a problem.
In the image below I show my global registry (the private one), and after that I install with success the hpe-sfdx-plugins package and then I try to install using ````sfdx plugins:install hpe-sfdx-plugins```` and it does not work.
![image](https://user-images.githubusercontent.com/55927613/82251489-363d4680-9945-11ea-8114-80384f9fcd8a.png)

**Comment by AllanOricil** [comment]
After debugging the code that installs the plugin. I was able to install the plugin from my private registry by changing this file locally

````...\sfdx\client\7.57.1-dbf54fc584\node_modules\@salesforce\sfdx-trust\dist\codeSigning\installationVerification.js````

````javascript
exports.getNpmRegistry = () => {
    return new url_1.URL('http://repo1.core.hpecorp.net/nexus/content/repositories/npm-internal' || exports.DEFAULT_REGISTRY);
};
````

Before that, I tried to setup the SFDX_NPM_REGISTRY env variable and it also fixed my issue. The package started to be located, but a new problem appeared. Sfdx started to look for ALL the dependencies from my private registry.

![image](https://user-images.githubusercontent.com/55927613/82256632-984e7980-994e-11ea-97ab-551f55fe31ae.png)

Then I discarded this solution and opted to hard code my registry directly in that getNpmRegistry line. And this was the result.

![image](https://user-images.githubusercontent.com/55927613/82257113-6558b580-994f-11ea-92f6-a7b7048342e0.png)


I think we need a new way of getting the Metadata of a package from a registry. Could you point me out to the github repository for this change? I can help to fix it if you need.

**Comment by amphro** [comment]
It correctly belongs here: https://github.com/forcedotcom/cli/issues/410
