### ISSUE TITLE
recordtype is retrievied into the compactlayout folders

### ISSUE THREAD

**Issue by mohametso** [forcedotcom/sfdx-core#276]
When running sfdx force:source:pull since few days, the recordtype is retrieved into the compactLayout folder. 
![image](https://user-images.githubusercontent.com/6200344/90259418-42547980-de4a-11ea-84b2-552114af449b.png)

**Comment by amphro** [comment]
This is an issue for https://github.com/forcedotcom/cli/issues - please fill out the bug report there.

**Comment by hassanalamibmx** [comment]
for people looking for updates, here is the link to the issue:
https://github.com/forcedotcom/cli/issues/602
