### ISSUE TITLE
PermissionSet

### ISSUE THREAD

**Issue by gagoy777** [forcedotcom/sfdx-core#364]
### Summary

We are able to deploy Permission set named Campaign Influence however we encounter error on assigning user permission with an error message Permission set "C" not found in target org. Do you need to push source?

### Steps To Reproduce:

1.  This is step 1. We deploy Permission set named Campaign Influence
1.  This is step 2. We then assign user permission using sfdx force:user:permset:assign -n "CampaignInfluence"

### Expected result

It should be deployed to the org

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 
sfdx-cli/7.84.2-a2868a68d5 win32-x64 node-v12.18.3
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
generator 1.1.3 (core)
salesforcedx 50.13.3 (core)
├─ user 1.0.5 (core)
├─ schema 1.0.3 (core)
├─ limits 1.0.2 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 50.13.1 (core)
├─ custom-metadata 1.0.11 (core)
├─ templates 50.4.0 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.84.2 (core)
**OS and version**:

**Comment by msrivastav13** [comment]
@gagoy777 I think you should close this and raise this on [this](https://github.com/forcedotcom/cli) repo

**Comment by ZeemanChen** [comment]
I had the same issue with the latest SFDX version (sfdx-cli/7.84.2-a2868a68d5), 
1. sfdx force:user:permset:assign not working properly.
2. sfdx force:user:create --definitionfile  
JSON:  "permsets": ["abc"]     not working properly as well

**Comment by gagoy777** [comment]
![image](https://user-images.githubusercontent.com/71573802/106109764-dca04380-6184-11eb-8a32-101f1d8d3120.png)

**Comment by gagoy777** [comment]
You just need to update the plugin using the `sfdx plugins:install user` @ZeemanChen
