### ISSUE TITLE
Unsecure .sfdx Folder and Files

### ISSUE THREAD

**Issue by JosephAllen** [forcedotcom/sfdx-core#386]
### Summary

Copying the contents of the [User]/.sfdx folder from one machine to another grants access to the new machine.

### Steps To Reproduce:

1. Create a scratch org  or auth an existing Sandbox / Prod Org
1. Install SFDX CLI on new machine
1. Copy contents of c:/users/[userName]/.sfdx to a new machine
1. Execute `sfdx force:org:display -u <Alias> --verbose` 

### Expected result

User should be required to login again. The key file, `key.json`, used for decrypting the Access and Refresh tokens should not be stored as a plain text file which can easily be cloned.

Quote from [Refresh Tokens: When to Use Them and How They Interact with JWTs](https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/)
> __Security considerations__
> 
> Refresh tokens are __long-lived__. This means when a client gets a refresh token from a server, this token must be __stored securely__ to keep it from being used by potential attackers. If a refresh token is leaked, it may be used to obtain new access tokens (and access protected resources) until it is either blacklisted or it expires (which may take a long time). Refresh tokens must be issued to a single authenticated client to prevent use of leaked tokens by other parties. Access tokens must be kept secret, but as you may imagine, security considerations are less strict due to their shorter life.

### Actual result

1. New machine renders verbose info about the authenticated org.
2. A __bad actor__ could easily use the files to access an org and reset passwords, manipulate data, etc.
3. The leaked refresh tokens, may be used to obtain new access tokens (and access protected resources) until they are either blacklisted or they expires (which may take a long time)
4. The leaked access tokens may be used to manually set passwords via Dev Console, `system.setPassword('005xx0000000XXX', 'passwordText')`. Imagine admins getting locked out of their own org.

### Additional information

**SFDX CLI Version**: sfdx-cli/7.89.2-d1d2614d02 win32-x64 node-v14.15.4

**OS and version**: Windows 10 Pro

**Comment by amphro** [comment]
https://github.com/forcedotcom/cli/issues/910
