### ISSUE TITLE
PollingClient can only call the poll method a maximum of 11 times before it times out.

### ISSUE THREAD

**Issue by sfryffdc** [forcedotcom/sfdx-core#430]
### Summary

Use the PollingClient

### Steps To Reproduce:

1. Create a PollingClient that will poll more than 11 times.
1. Call subscribe
1. wait

### Expected result

It keeps polling until complete.

### Actual result

Always only tries 11 times. The initial plus the default retries for the retry library you are using.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
N/A

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
N/A

**OS and version**:
Linux Debian Buster.

**Comment by sfryffdc** [comment]
Thanks for the quick turn around!

**Comment by shetzel** [comment]
@sfryffdc - sorry for the regression!  We switched the internal implementation to a new polling library and missed that it defaults to a max of 10 polling attempts.  Sometime in the future, we'd like to expose some other features of the library such as backoff strategy.
