### ISSUE TITLE
VSCode Extensions fail to launch

### ISSUE THREAD

**Issue by NuAgeDan** [forcedotcom/sfdx-core#464]
System info:
SFDX Version: 7.112.1 (latest)
Extension versions: 52.8 (I believe the latest)
OS: Windows 10 19042.1110  (latest)

When you open an SFDX project in VSCode, extensions should launch automatically, they don't for me. I have to run the replay debugger (the only icon that appears) and wait 5-10 minutes for them to open. During this time, VSCode makes considerable calls to the HD (~10mb/s). Presumably the extensions aren't 3-6GB, and should open on their own.

**Comment by mshanemc** [comment]
That belongs here: https://github.com/forcedotcom/salesforcedx-vscode
