### ISSUE TITLE
postorgcreate emitted twice - in addition first hook is emitted without await

### ISSUE THREAD

**Issue by gitfish** [forcedotcom/sfdx-core#634]
### Summary

This is specific to version 3.x in conjunction with the org plugin. The org plugin will ultimately call the core method scratchOrgCreate (in the org/scratchOrgCreate module). The scratchOrgCreate method will call emitPostOrgCreate (from org/scratchOrgLifecycleEvents) which emits the lifecycle event `postorgcreate` - this is emitted without an await (so it's properly async). The issue is that the org plugin also emits the lifecycle event `postorgcreate`, so we're effectively getting the hook firing twice, with the first invocation effectively being in parallel with the second.

Here are the code links to the two firings:
- https://github.com/salesforcecli/plugin-org/blob/fbbcaf5d816c9e0e6040a2d5cb6690cdb6356674/src/commands/force/org/create.ts#L320

- https://github.com/forcedotcom/sfdx-core/blob/050d7c5a7f49b85895c74422ebbb0494fcf0cb96/src/org/scratchOrgCreate.ts#L178

### Steps To Reproduce:

1.  Register a postorgcreate hook - a hook that just logs to the console will be sufficient
2.  Create a scratch org

### Expected result

A specific `postorgcreate` hook should only fire once

### Actual result

The specific `postorgcreate` hook fires twice

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.166.1 darwin-x64 node-v16.14.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):

@oclif/plugin-autocomplete 1.3.0 (core)
@oclif/plugin-commands 2.2.0 (core)
@oclif/plugin-help 5.1.12 (core)
@oclif/plugin-not-found 2.3.1 (core)
@oclif/plugin-plugins 2.1.0 (core)
@oclif/plugin-update 3.0.0 (core)
@oclif/plugin-version 1.1.2 (core)
@oclif/plugin-warn-if-update-available 2.0.4 (core)
@oclif/plugin-which 2.1.0 (core)
@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)
alias 2.1.0 (core)
apex 1.2.0 (core)
auth 2.2.3 (core)
community 2.0.1 (core)
config 1.4.17 (core)
custom-metadata 2.0.0 (core)
data 2.1.2 (core)
generator 2.0.2 (core)
info 2.0.1 (core)
limits 2.0.1 (core)
org 2.2.0 (core)
packaging 1.5.1 (core)
salesforce-alm 54.8.1 (core)
schema 2.1.1 (core)
sfdx-bfs-plugin 2.0.0-1 (link) /usr/local/lib/node_modules/sfdx-bfs-plugin
sfdx-cli 7.166.1 (core)
signups 1.2.0 (core)
source 2.0.13 (core)
telemetry 2.0.0 (core)
templates 55.1.0 (core)
trust 2.0.3 (core)
user 2.1.0 (core)

NOTE: this sfdx-bfs-plugin is not publicly available and is the plugin containing the hooks I'm using to test.

**OS and version**: Mac OS Version 12.5.1

**Comment by mshanemc** [comment]
will fix on the plugin and leave here in core

**Comment by gitfish** [comment]
I still think you need to fix core as it's invoked without await. In addition, looking at the version 4 source, it looks like the postorgcreate emit has been removed from core, so if you remove it from the plugin there'll be no event emitted.

**Comment by mshanemc** [comment]
ignore version 4...that's some kind of weird CI mistake
