### ISSUE TITLE
Incorrect URL for scratch org error codes in messages/scratchOrgErrorCodes.md

### ISSUE THREAD

**Issue by agomez-sf** [forcedotcom/sfdx-core#680]
### Summary

Url in scratchOrgErrorCodes.md does not point to the documentation for error codes

### Steps To Reproduce:

1.  Create scratch org with no active scratch source org
1.  Click link in error message

### Expected result

Link redirects user to https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_error_codes.htm 

### Actual result

Link redirects user to https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_signuprequest.htm 

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):

**OS and version**:

**Comment by cristiand391** [comment]
Fixed in the linked PR above, thanks for contributing :)
