### ISSUE TITLE
Update JSForce type definitions

### ISSUE THREAD

**Issue by catalandres** [forcedotcom/sfdx-core#81]
Bandwidth permitting, please update the type definitions for JSForce — there was a typo in the metadata describe results and the PR that fixes it just got merged (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31605).

**Comment by rbergman** [comment]
For this case we can probably update just the jsforce types, which we did before releasing 1.x.  The actual jsforce package has incompatible changes in 1.9.1 last we checked.  /cc @tnoonan-salesforce

**Comment by catalandres** [comment]
In the changes that I proposed, `yarn test` did pass.
Are there tests that we can add to detect and mitigate the regression?

**Comment by rbergman** [comment]
We had the same experience (with core UTs passing) when we tried updating to 1.9.1.  The tests in this case are part of our internal command unit test and integration test suites.  To cover all of jsforce in core tests isn't really feasible, unfortunately.

**Comment by clairebianchi** [comment]
Waiting for PR updates
