### ISSUE TITLE
Module '"@salesforce/core"' has no exported member 'fs'

### ISSUE THREAD

**Issue by dewanshu-verma** [forcedotcom/sfdx-core#823]
While using:
import { fs } from '@salesforce/core'
fs.readJsonMap function

I'm getting the error: Module '"@salesforce/core"' has no exported member 'fs'
What is the alternate or workaround for this?

Versions Information:
SFDX CLI: sfdx-cli/7.197.8 darwin-arm64 node-v18.14.0
salesforce/core: 3.34.8

**Comment by cristiand391** [comment]
Hi @dewanshu-verma 
the `fs` module was removed in sfdx-core v3, it was mostly a wrapper around node's fs so you can do the same using the native API.
Here's the code for v2:
https://github.com/forcedotcom/sfdx-core/blob/2f917420d2f004128f538fb8f8ca2432f70bddf9/src/util/fs.ts#L221

**Comment by cristiand391** [comment]
@dewanshu-verma I linked the code for `readJsonMap` above, you can see it's using `fs.readFile` and `parseJsonMap` from `@salesforce/kit`.
