### ISSUE TITLE
Error during force:web:auth:login on Linux

### ISSUE THREAD

**Issue by sauloefo** [forcedotcom/sfdx-core#83]
Hi Guys,

I am facing an issue with SFDX on Linux. It seems to be a bug once I am not facing the same issue on MacOS X for the same steps.

**Environment:**
OS: Linux Mint 19.1 (Cinnamon)
SFDX: sfdx-cli/6.44.0-dead729fb5 (linux-x64) node-v8.9.4.

**Steps to reproduce:**
1) type `sfdx force:auth:web:login -d -a myorg` on terminal;
2) Fill the login credentials properly and log in.

**Expected behaviour:**
1) Redirect into the org
2) receive the message on terminal asking me to close the browse.

**Behaviour experienced:**
1) Redirect to a non existent local address: http://localhost:1717/OauthRedirect?code=aPrxSV6UAcNrPEk0y7Ktjn1KapgXd8gNZ3kCzMh8vMEHlIEWpfqZ4Qi.Sm9rwTMF1wVncBmHhA%3D%3D&state=5f952686ee36  
2) receive the message bellow on terminal:
    _ERROR:  The service and account specified in /home/saulo/.sfdx/key.json do not match the version of the toolbelt. 
    Try this:
    Check your toolbelt version and re-auth._

**Info**
1) I have tried execute with sudo. Same result.
2) As I have mentioned earlier, I did the same procedure on MacOS X and no issues happened.
3) I am using `node v10.15.0` managed by `nvm v0.33.10`.

**Comment by sauloefo** [comment]
@amphro you save my day! I deleted key.json file and the authorization process works perfectly! Thanks a million for your help!

**Comment by lodossDev** [comment]
Hi I am also having this issue on our jenkins build machine, I have deleted the key.json file callinf auth again just repeats the same error?

**Comment by lodossDev** [comment]
The jenkins machine is on linux.

I have set no env variables.

I am pretty sure it created the key.json again probably blank though.

The home dir was at home/jenkins/.sfdx

**Comment by lodossDev** [comment]
@amphro 

any possible suggestions?

**Comment by amphro** [comment]
Can you confirm that it is *not* blank. That will probably cause problems too. Could there be any way multiple users are trying to access that file or is it all under the jenkins user?

**Comment by lodossDev** [comment]
@amphro 

I can confirm the key.json is created again, but blank.
Everything is running under the jenkins user, no one else should be accessing that location?

**Comment by lodossDev** [comment]
@amphro 

also the jenkins build is running on a docker container, so its a fresh machine every time?

**Comment by gitmevg** [comment]
I know that the thread has been closed... Just wanted to confirm if there has been a fix identified for below error as reported previously over Jenkins Server during:

sfdx force:auth:jwt:grant --clientid XXXXX --username XXXXX --jwtkeyfile XXXXX --setdefaultdevhubusername --instanceurl https://test.salesforce.com

ERROR: Command failed with response. - (secret-tool:20489): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed secret-tool: Cannot autolaunch D-Bus without X11 $DISPLAY

Appreciate help over here as I am stuck for a while...

**Comment by dieffrei** [comment]
I had the same problem reported from @lodossDev in Jenkins CI using docker.
@lodossDev did you find the solution?

**Comment by dvon88** [comment]
I am now having this same issue (as original post), except I do not have a key file in the .sfdx folder. No key file is created, and there is none to delete

**Comment by clemb08** [comment]
Hello I'm experiencing the same issue (as original post), I deleted the key file in the .sfdx folder but none is created when I try to do a new Authorization, someone has a way to fix this ?

**Comment by Sharif6529** [comment]
What is the solution for this?
