### ISSUE TITLE
Libsecret secret-tool: Cannot autolaunch D-Bus without X11 $DISPLAY during authentication

### ISSUE THREAD

**Issue by lodossDev** [forcedotcom/sfdx-core#91]
### Summary

When using linux (Centos7) Jenkins docker container and using libsecret as default keychain access the following error occurs during authentication:

(secret-tool:1000): GLib-GObject-CRITICAL **: 19:35:38.194: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
secret-tool: Cannot autolaunch D-Bus without X11 $DISPLAY

### Steps To Reproduce:

When creating a plugin using the sfdx plugin sdk and running the following code:

const authInfo = await AuthInfo.create(conn.accessToken);
     
        await authInfo.save({
            username: this.flags.username,
            password: this.flags.password,
            clientId: clientid,
            clientSecret: secret,
            loginUrl: this.flags.server,
            instanceUrl: conn.instanceUrl,
            orgId: userInfo.organizationId
        });

**Comment by tnoonan-salesforce** [comment]
So libsecret won't work without an X11 host.

Instead, add this environment variable:

export SFDX_USE_GENERIC_KEYCHAIN=true

**Comment by rickloveslamp** [comment]
That env variable didn't work for me. According to the [developer guide](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_env_variables.htm) it should be:
`export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true`

**Comment by shetzel** [comment]
Apologies!  That was a typo.  SFDX_USE_GENERIC_UNIX_KEYCHAIN is the correct env var.

**Comment by sudhir6199** [comment]
Really Worked thankyou @shetzel & @rickloveslamp  really my day saved .Thankyouuuuuuuuuuuuuuuuuuuuuuu soooooooooo muchhhhhhhhhh 💃  👯‍♂

**Comment by PremChavhan** [comment]
Guys using Jenkins please add SFDX_USE_GENERIC_UNIX_KEYCHAIN in Jenkins environment variables

**Comment by ashutosh28backup** [comment]
@PremChavhan : Tried using the environment variable and exporting the SFDX_USE_GENERIC_UNIX_KEYCHAIN as well. It did not work. Still getting the same error:
ERROR running auth:jwt:grant:  We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: Command failed with response:
 -
(secret-tool:13882): GLib-GObject-CRITICAL **: 11:59:29.911: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
secret-tool: Cannot autolaunch D-Bus without X11 $DISPLAY

Can anyone please help !

**Comment by c-prado** [comment]
@ashutosh28backup have you installed sfdx cli or just download? Does the user executing the scripts have permission in all needed directories?
